changelog:
  exclude:
    labels:
      - 'skip-changelog'
  categories:
    - title: Security and infrastructure
      labels:
        - 'security'
        - 'infrastructure'
    - title: Features
      labels:
        - 'enhancement'
    - title: Bug fixes
      labels:
        - 'bug'
    - title: Other changes
      labels:
        - '*'
